version: '3'

services:

  irods_a:
    hostname: $host_name_A
    build:
      context: .
      dockerfile: Dockerfile.icat
      args:
        zone_key: ${zone_key_A}
        negotiation_key: ${negotiation_key_A}
        zone_name: ${zone_name_A}
        zone_port: ${zone_port_A}
        federate_with: "([zp]=$zone_port_B [hn]=$host_name_B [zn]=$zone_name_B [nk]=$negotiation_key_B [zk]=$zone_key_B)"
    networks:
      default:
        aliases:
          - $host_name_A

  irods_b:
    hostname: $host_name_B
    build:
      context: .
      dockerfile: Dockerfile.icat
      args:
        zone_key: ${zone_key_B}
        negotiation_key: ${negotiation_key_B}
        zone_name: ${zone_name_B}
        zone_port: ${zone_port_B}
    networks:
      default:
        aliases:
          - $host_name_B

